"""add campaign offer config

The copywriting agent takes an OfferConfig -- who is sending and what they
are selling -- and there was nowhere to store one. The agent was fully
built and tested since Session 13, but no campaign could actually supply
it, so copy generation could never run against real data.

Per campaign rather than global: one user legitimately runs different
offers to different audiences, and the copy hangs entirely off this.

Server default '{}' so existing rows get an empty offer rather than NULL.
The copy stage refuses to run on an empty offer instead of writing an
email signed by nobody about nothing.

Revision ID: 27ad8eeee9e5
Revises: 811d3b3c7672
Create Date: 2026-08-22 13:06:38.684022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27ad8eeee9e5'
down_revision: Union[str, Sequence[str], None] = '811d3b3c7672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required, not cosmetic: autogenerate omits it, and
    # adding a NOT NULL column without one fails outright on a table that
    # already has rows.
    op.add_column(
        'campaigns',
        sa.Column(
            'offer',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'offer')
    # ### end Alembic commands ###
