"""scope company place-id uniqueness to campaign

`companies.source_place_id` was UNIQUE globally, but the row carries a
NOT NULL `campaign_id` and is therefore campaign-scoped data. The two
facts contradict each other: the first campaign to discover a business
permanently claimed its place id, so every later campaign targeting the
same area lost that business to a constraint violation on insert. With
several campaigns running over overlapping geography -- the normal case --
leads would go silently missing.

Re-scoping to (campaign_id, source_place_id) keeps discovery idempotent
within a campaign, which is what the dedup was actually for, while letting
two campaigns each hold their own row for the same real-world business.

The downgrade can fail on purpose: once two campaigns both hold the same
place id, restoring a global unique constraint is not possible without
deleting data, and this migration will not choose which campaign loses
its leads.

Revision ID: 7ed091f9c1fc
Revises: a22d64ab30ca
Create Date: 2026-08-22 12:14:34.503902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed091f9c1fc'
down_revision: Union[str, Sequence[str], None] = 'a22d64ab30ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('companies_source_place_id_key'), 'companies', type_='unique')
    op.create_unique_constraint('uq_companies_campaign_place', 'companies', ['campaign_id', 'source_place_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_companies_campaign_place', 'companies', type_='unique')
    op.create_unique_constraint(op.f('companies_source_place_id_key'), 'companies', ['source_place_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
