"""make email verified_at timezone aware

`email_addresses.verified_at` was the only datetime column in the schema
declared without `timezone=True`, so Postgres created it as TIMESTAMP
WITHOUT TIME ZONE. Writing an aware UTC datetime to it failed outright,
and a naive one would have silently recorded whatever local time the
worker happened to be running in.

app/db/base.py's docstring calls this out as irrecoverable corruption:
the sending engine converts stored timestamps to the recipient's local
time, and a timestamp that has already lost its offset cannot be
converted back. Existing rows are reinterpreted as UTC on upgrade, which
is correct for any row written by this codebase -- everything here
constructs timestamps with datetime.now(UTC).

Revision ID: 811d3b3c7672
Revises: 7ed091f9c1fc
Create Date: 2026-08-22 12:28:04.429833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '811d3b3c7672'
down_revision: Union[str, Sequence[str], None] = '7ed091f9c1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_addresses', 'verified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_addresses', 'verified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
