"""extend hooks table

Revision ID: a22d64ab30ca
Revises: d07e596b4843
Create Date: 2026-08-17 10:46:23.672375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22d64ab30ca'
down_revision: Union[str, Sequence[str], None] = 'd07e596b4843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    `hooks` has no writers yet (Session 12 is what adds them), but this
    still gives the new NOT NULL columns real defaults rather than relying
    on that -- the same discipline as every other migration in this
    project, and cheap insurance against the day something has written a
    row before this lands. `status` has no sensible default (a verdict is
    never optional) so it stays a hard requirement.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # add_column(), unlike create_table(), does NOT auto-create the
    # Postgres enum type it references -- SQLAlchemy only does that as a
    # side effect of CREATE TABLE. Each type must be created explicitly
    # first, or the ALTER TABLE below fails with "type does not exist".
    bind = op.get_bind()
    sa.Enum('FOUND', 'NONE_FOUND', name='hook_verdict').create(bind, checkfirst=True)
    sa.Enum(
        'NEW_LOCATION', 'AWARD', 'ANNIVERSARY', 'NEW_HIRE', 'HIRING',
        'EXPANDED_HOURS', 'PROMO', 'PRESS', 'OTHER', 'NONE', name='hook_news_type',
    ).create(bind, checkfirst=True)
    sa.Enum(
        'WEBSITE', 'INSTAGRAM', 'FACEBOOK', 'LINKEDIN', 'PRESS',
        'DIRECTORY', 'OTHER', 'NONE', name='hook_channel',
    ).create(bind, checkfirst=True)
    sa.Enum('HIGH', 'MEDIUM', 'LOW', name='hook_confidence_level').create(bind, checkfirst=True)

    op.add_column('hooks', sa.Column('status', sa.Enum('FOUND', 'NONE_FOUND', name='hook_verdict'), nullable=False))
    op.add_column('hooks', sa.Column('event_date', sa.Date(), nullable=True))
    op.add_column('hooks', sa.Column('news_type', sa.Enum('NEW_LOCATION', 'AWARD', 'ANNIVERSARY', 'NEW_HIRE', 'HIRING', 'EXPANDED_HOURS', 'PROMO', 'PRESS', 'OTHER', 'NONE', name='hook_news_type'), nullable=False, server_default='NONE'))
    op.add_column('hooks', sa.Column('channel', sa.Enum('WEBSITE', 'INSTAGRAM', 'FACEBOOK', 'LINKEDIN', 'PRESS', 'DIRECTORY', 'OTHER', 'NONE', name='hook_channel'), nullable=False, server_default='NONE'))
    op.add_column('hooks', sa.Column('swap_test_passed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('hooks', sa.Column('needs_review', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('hooks', sa.Column('notes', sa.String(), nullable=False, server_default=''))
    op.add_column('hooks', sa.Column('transcript', sa.Text(), nullable=True))
    op.add_column('hooks', sa.Column('model', sa.String(), nullable=True))
    op.add_column('hooks', sa.Column('cost_usd', sa.Float(), nullable=True))
    op.alter_column('hooks', 'hook_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hooks', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hooks', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Enum('HIGH', 'MEDIUM', 'LOW', name='hook_confidence_level'),
               existing_nullable=False,
               postgresql_using="'LOW'::hook_confidence_level")
    # ### end Alembic commands ###

    # Server defaults above exist only to satisfy the NOT NULL backfill for
    # any pre-existing rows; the ORM model sets its own Python-side
    # defaults for new inserts, so drop the server ones to keep one source
    # of truth (matches the original core-schema migration's columns).
    op.alter_column('hooks', 'news_type', server_default=None)
    op.alter_column('hooks', 'channel', server_default=None)
    op.alter_column('hooks', 'swap_test_passed', server_default=None)
    op.alter_column('hooks', 'needs_review', server_default=None)
    op.alter_column('hooks', 'notes', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hooks', 'confidence',
               existing_type=sa.Enum('HIGH', 'MEDIUM', 'LOW', name='hook_confidence_level'),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               postgresql_using="0.0")
    op.alter_column('hooks', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hooks', 'hook_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('hooks', 'cost_usd')
    op.drop_column('hooks', 'model')
    op.drop_column('hooks', 'transcript')
    op.drop_column('hooks', 'notes')
    op.drop_column('hooks', 'needs_review')
    op.drop_column('hooks', 'swap_test_passed')
    op.drop_column('hooks', 'channel')
    op.drop_column('hooks', 'news_type')
    op.drop_column('hooks', 'event_date')
    op.drop_column('hooks', 'status')
    # ### end Alembic commands ###

    # See d07e596b4843_core_schema.py's downgrade for why this is explicit:
    # autogenerate's downgrade doesn't drop the enum types it created, and
    # a later `upgrade head` fails with "type already exists" otherwise.
    for enum_name in ("hook_confidence_level", "hook_channel", "hook_news_type", "hook_verdict"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
