"""core schema

Revision ID: d07e596b4843
Revises: 
Create Date: 2026-08-15 00:29:58.489961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd07e596b4843'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icp', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'DISCOVERING', 'ENRICHING', 'RESEARCHING', 'WRITING', 'READY', 'SENDING', 'PAUSED', 'COMPLETED', name='campaign_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_patterns',
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('confirmed_count', sa.Integer(), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_patterns_domain'), 'domain_patterns', ['domain'], unique=True)
    op.create_table('facts',
    sa.Column('subject_type', sa.Enum('COMPANY', 'PERSON', 'EMAIL', name='subject_type'), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('independence_key', sa.String(), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_facts_conf'),
    sa.ForeignKeyConstraint(['superseded_by'], ['facts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facts_subject', 'facts', ['subject_type', 'subject_id', 'field'], unique=False)
    op.create_table('mailboxes',
    sa.Column('provider', sa.Enum('GOOGLE_WORKSPACE', 'MICROSOFT_365', 'GENERIC_SMTP', name='mailbox_provider'), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('encrypted_credentials', sa.LargeBinary(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('warmup_stage', sa.Integer(), nullable=False),
    sa.Column('daily_cap', sa.Integer(), nullable=False),
    sa.Column('dns_status', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('resolver_runs',
    sa.Column('resolver', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Enum('HIT', 'MISS', 'ERROR', 'SKIPPED', name='resolver_outcome'), nullable=False),
    sa.Column('candidates_returned', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolver_runs_resolver'), 'resolver_runs', ['resolver'], unique=False)
    op.create_index(op.f('ix_resolver_runs_subject_id'), 'resolver_runs', ['subject_id'], unique=False)
    op.create_table('suppressions',
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppressions_value'), 'suppressions', ['value'], unique=True)
    op.create_table('companies',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source_place_id', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_place_id')
    )
    op.create_index(op.f('ix_companies_campaign_id'), 'companies', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_table('seed_tests',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('mailbox_address', sa.String(), nullable=False),
    sa.Column('placement', sa.Enum('INBOX', 'PROMOTIONS', 'SPAM', 'NOT_FOUND', 'UNKNOWN', name='seed_placement'), nullable=False),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seed_tests_campaign_id'), 'seed_tests', ['campaign_id'], unique=False)
    op.create_table('hooks',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('hook_text', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('found_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hooks_company_id'), 'hooks', ['company_id'], unique=False)
    op.create_table('people',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('role_class', sa.Enum('OWNER', 'MANAGER', 'MARKETING', 'OTHER', name='role_class'), nullable=False),
    sa.Column('seniority', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_company_id'), 'people', ['company_id'], unique=False)
    op.create_table('email_addresses',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('pattern_used', sa.String(), nullable=True),
    sa.Column('verify_status', sa.Enum('UNCHECKED', 'VALID', 'INVALID', 'CATCH_ALL', 'UNKNOWN', 'ROLE', name='verify_status'), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_role_account', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_addresses_address'), 'email_addresses', ['address'], unique=False)
    op.create_index(op.f('ix_email_addresses_company_id'), 'email_addresses', ['company_id'], unique=False)
    op.create_index(op.f('ix_email_addresses_person_id'), 'email_addresses', ['person_id'], unique=False)
    op.create_table('messages',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('angle', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('quality_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'REJECTED', 'SENT', name='message_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_company_id'), 'messages', ['company_id'], unique=False)
    op.create_table('sends',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('mailbox_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'BOUNCED', 'FAILED', name='send_status'), nullable=False),
    sa.Column('message_id_header', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sends_mailbox_id'), 'sends', ['mailbox_id'], unique=False)
    op.create_index(op.f('ix_sends_message_id'), 'sends', ['message_id'], unique=False)
    op.create_table('replies',
    sa.Column('send_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.Enum('INTERESTED', 'NOT_INTERESTED', 'OUT_OF_OFFICE', 'WRONG_PERSON', 'UNSUBSCRIBE', 'AUTO_REPLY', 'BOUNCE', name='reply_classification'), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_snippet', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['send_id'], ['sends.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replies_send_id'), 'replies', ['send_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replies_send_id'), table_name='replies')
    op.drop_table('replies')
    op.drop_index(op.f('ix_sends_message_id'), table_name='sends')
    op.drop_index(op.f('ix_sends_mailbox_id'), table_name='sends')
    op.drop_table('sends')
    op.drop_index(op.f('ix_messages_company_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_email_addresses_person_id'), table_name='email_addresses')
    op.drop_index(op.f('ix_email_addresses_company_id'), table_name='email_addresses')
    op.drop_index(op.f('ix_email_addresses_address'), table_name='email_addresses')
    op.drop_table('email_addresses')
    op.drop_index(op.f('ix_people_company_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_hooks_company_id'), table_name='hooks')
    op.drop_table('hooks')
    op.drop_index(op.f('ix_seed_tests_campaign_id'), table_name='seed_tests')
    op.drop_table('seed_tests')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_index(op.f('ix_companies_campaign_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_suppressions_value'), table_name='suppressions')
    op.drop_table('suppressions')
    op.drop_index(op.f('ix_resolver_runs_subject_id'), table_name='resolver_runs')
    op.drop_index(op.f('ix_resolver_runs_resolver'), table_name='resolver_runs')
    op.drop_table('resolver_runs')
    op.drop_table('mailboxes')
    op.drop_index('ix_facts_subject', table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_domain_patterns_domain'), table_name='domain_patterns')
    op.drop_table('domain_patterns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###

    # Alembic's autogenerate emits op.drop_table() calls directly, which do
    # NOT drop the Postgres enum types those columns used (only a
    # metadata-aware `metadata.drop_all()` does that automatically). Left
    # unhandled, `downgrade base` leaves every enum type orphaned in the
    # schema, and a subsequent `upgrade head` fails with "type already
    # exists". Drop them explicitly, after every table that references them
    # is already gone.
    for enum_name in (
        "reply_classification",
        "send_status",
        "message_status",
        "verify_status",
        "role_class",
        "seed_placement",
        "mailbox_provider",
        "resolver_outcome",
        "subject_type",
        "campaign_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
