"""Refresh app/llm/model_prices.json from OpenRouter's live model catalogue.

The file this rewrites was hand-maintained, and hand-maintained price data
goes wrong quietly: it listed DeepSeek V4 Flash at $0.028/$0.088 when the
real price was $0.071/$0.143 (2.5x understated), and had no entry at all
for V4 Pro -- which made `PriceTable` record every V4 Pro call as costing
$0, leaving `SpendCap` unable to see the spend it exists to stop.

OpenRouter publishes live per-token pricing for models across every major
vendor at /api/v1/models, so one fetch covers Anthropic, OpenAI, Google,
DeepSeek, Alibaba and the rest. No API key is needed for the catalogue.

Run:  uv run python scripts/refresh_prices.py

Entries are written under both the prefixed id ("anthropic/claude-sonnet-5")
and the bare id ("claude-sonnet-5"), because a direct-provider adapter asks
for the model by its native name while OpenRouter asks for the prefixed one
-- `PriceTable` looks up whatever string the gateway used.
"""

from __future__ import annotations

import json
import sys
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

import httpx

CATALOGUE_URL = "https://openrouter.ai/api/v1/models"
PRICES_FILE = Path(__file__).resolve().parent.parent / "app" / "llm" / "model_prices.json"

COMMENT = (
    "Generated by scripts/refresh_prices.py from OpenRouter's live catalogue -- "
    "do not hand-edit, re-run the script instead. PriceTable warns when this file "
    "is older than MAX_PRICE_AGE_DAYS rather than silently reporting wrong costs."
)


def _per_million(per_token: str | float | None) -> Decimal | None:
    """OpenRouter quotes per-token; the table stores per-million."""
    if per_token is None:
        return None
    try:
        value = Decimal(str(per_token)) * 1_000_000
    except (ArithmeticError, ValueError):
        return None
    # Free models quote 0; keep them, they are legitimately free.
    return value if value >= 0 else None


def _normalise(raw: str) -> str:
    """Trim OpenRouter's routing decorations (a leading '~' marks a
    floating 'latest' alias) so ids match what a gateway actually sends.
    """
    return raw.lstrip("~")


def build_price_map(models: list[dict[str, Any]]) -> dict[str, dict[str, float]]:
    prices: dict[str, dict[str, float]] = {}

    for model in models:
        model_id = _normalise(str(model.get("id", "")))
        if not model_id:
            continue

        pricing = model.get("pricing") or {}
        prompt = _per_million(pricing.get("prompt"))
        completion = _per_million(pricing.get("completion"))
        if prompt is None or completion is None:
            continue

        entry = {"prompt": float(prompt), "completion": float(completion)}
        prices[model_id] = entry

        # Also index the bare name for direct-provider adapters, but never
        # let a bare alias overwrite a differently-priced sibling: the first
        # (cheapest-sorted) wins deterministically rather than by dict order.
        _, _, bare = model_id.partition("/")
        if bare and bare not in prices:
            prices[bare] = entry

    return prices


def main() -> int:
    print(f"fetching {CATALOGUE_URL} ...")
    try:
        response = httpx.get(CATALOGUE_URL, timeout=30.0)
        response.raise_for_status()
    except httpx.HTTPError as exc:
        print(f"FAILED: {exc}", file=sys.stderr)
        return 1

    models = response.json().get("data", [])
    if not models:
        print("FAILED: catalogue returned no models", file=sys.stderr)
        return 1

    prices = build_price_map(models)
    if not prices:
        print("FAILED: no usable pricing in catalogue", file=sys.stderr)
        return 1

    payload = {
        "fetched_at": datetime.now(UTC).date().isoformat(),
        "currency": "USD",
        "unit": "per_million_tokens",
        "source": CATALOGUE_URL,
        "_comment": COMMENT,
        "models": dict(sorted(prices.items())),
    }

    PRICES_FILE.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    repo_root = PRICES_FILE.parent.parent.parent
    print(f"wrote {len(prices)} entries to {PRICES_FILE.relative_to(repo_root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
